# Generated by Django 3.1.6 on 2021-04-06 20:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyfinder', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Please update your bio!'),
        ),
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='cleanliness_level',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(default='wyy3pna3gxgiafzyvn4g', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='morning_preference',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='noise_level',
            field=models.IntegerField(default=2),
        ),
    ]
