# Generated by Django 3.1.7 on 2021-04-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyfinder', '0003_auto_20210413_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_artist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_link',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_song',
            field=models.CharField(default='', max_length=100),
        ),
    ]
