# Generated by Django 3.1.7 on 2021-04-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyfinder', '0004_auto_20210418_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spotify_artist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='spotify_link',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='spotify_song',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
