# Generated by Django 3.1.6 on 2021-04-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddyfinder', '0005_auto_20210418_1323'),
        ('buddyfinder', '0005_auto_20210418_1355'),
    ]

    operations = [
    ]
