# Generated by Django 3.1.6 on 2021-04-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyfinder', '0006_merge_20210418_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
