# Generated by Django 3.1.7 on 2021-05-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyfinder', '0007_auto_20210418_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cleanliness_level',
            field=models.CharField(default='Neutral', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='morning_preference',
            field=models.CharField(default='Neutral', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='noise_level',
            field=models.CharField(default='Neutral', max_length=200),
        ),
    ]
